apiVersion: apps/v1
kind: Deployment
metadata:
  name: asguconfigserver
  labels:
    app: asguconfigserver
spec:
  replicas: 1
  selector:
    matchLabels:
      service: asguconfigserver
  template:
    metadata:
      labels:
        app: asguconfigserver
        service: asguconfigserver
    spec:
      containers:
        - name: webapp
          image: asguconfigserver.azurecr.io/asguconfigserver:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8888
            - name: WebApiBaseAddress
              value: http://webapi