apiVersion: v1
kind: Service
metadata:
  name: cloudconfigserver
  labels:
    app: sample-app
    service: cloudconfigserver
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    service: cloudconfigserver