apiVersion: v1
kind: Service
metadata:
  name: asguconfigserver
  labels:
    app: asguconfigserver
    service: asguconfigserver
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    service: asguconfigserver